name: Unit Tests

on:
  push:
    branches:
        - main
  pull_request:
  workflow_dispatch:

jobs:
  unit-test:
    name: Linux Tests
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Install dldock
        run: pip install .
      - name: Run Unit Tests
        run: pytest tests
